apiVersion: 1

datasources:
  - name: DocsAssistantDB
    uid: docs-assistant-pg
    type: grafana-postgresql-datasource
    access: proxy
    url: postgres:5432
    user: $POSTGRES_USER
    jsonData:
      database: $POSTGRES_DB
      sslmode: disable
      maxOpenConns: 5
    secureJsonData:
      password: $POSTGRES_PASSWORD
    isDefault: true
    editable: true
